package com.meshbbs.setup;
/** Hardware IDs reported by Meshtastic; never inferred from a Bluetooth name. */
public final class RadioModels {
  private RadioModels() {}
  public static String name(int id) {
    switch(id) {
      case 1: return "LILYGO T-LoRa V2";
      case 2: return "LILYGO T-LoRa V1";
      case 3: return "LILYGO T-LoRa V2.1-1.6";
      case 4: return "LILYGO T-Beam";
      case 5: return "Heltec V2.0";
      case 6: return "LILYGO T-Beam V0.7";
      case 7: return "LILYGO T-Echo";
      case 8: return "LILYGO T-LoRa V1.1-1.3";
      case 9: return "RAK WisBlock 4631 / RAK WisMesh Pocket V3 / RAK WisMesh Repeater Mini V2";
      case 10: return "Heltec V2.1";
      case 11: return "Heltec V1";
      case 12: return "LILYGO T-Beam Supreme";
      case 13: return "RAK WisBlock 11200";
      case 14: return "Nano G1";
      case 15: return "LILYGO T-LoRa V2.1-1.8";
      case 16: return "LILYGO T-LoRa T3-S3 / LILYGO T-LoRa T3-S3 E-Ink";
      case 17: return "Nano G1 Explorer";
      case 18: return "Nano G2 Ultra";
      case 21: return "Seeed Wio WM1110 Tracker";
      case 25: return "Station G1";
      case 26: return "RAK WisBlock 11310";
      case 29: return "Canary One";
      case 30: return "RP2040 LoRa";
      case 31: return "Station G2";
      case 33: return "LILYGO T-Echo Plus";
      case 39: return "DIY V1 / Hydra";
      case 41: return "DR-DEV";
      case 42: return "M5 Stack";
      case 43: return "Heltec V3";
      case 44: return "Heltec Wireless Stick Lite V3";
      case 47: return "Raspberry Pi Pico / Raspberry Pi Pico W";
      case 48: return "Heltec Wireless Tracker V1.1 / TrackSenger (small TFT) / TrackSenger (big TFT) / TrackSenger (big OLED)";
      case 58: return "Heltec Wireless Tracker V1.0";
      case 49: return "Heltec Wireless Paper";
      case 50: return "LILYGO T-Deck";
      case 51: return "LILYGO T-Watch S3";
      case 52: return "Pi Computer S3";
      case 53: return "Heltec HT62";
      case 57: return "Heltec Wireless Paper V1.0";
      case 59: return "unPhone";
      case 61: return "EBYTE EoRa-S3";
      case 64: return "RadioMaster 900 Bandit Nano";
      case 66: return "Heltec Vision Master T190";
      case 67: return "Heltec Vision Master E213";
      case 68: return "Heltec Vision Master E290";
      case 69: return "Heltec Mesh Node T114";
      case 70: return "Seeed SenseCAP Indicator";
      case 71: return "Seeed Card Tracker T1000-E";
      case 81: return "Seeed Xiao ESP32-S3";
      case 105: return "RAK WisMesh Tag";
      case 84: return "RAK WisMesh Tap";
      case 22: return "RAK WisMesh Repeater";
      case 63: return "NRF52 Pro-micro DIY";
      case 88: return "Seeed Xiao NRF52840 Kit";
      case 89: return "ThinkNode M1";
      case 107: return "ThinkNode M5";
      case 90: return "ThinkNode M2";
      case 93: return "muzi BASE DUO/UNO";
      case 94: return "Heltec MeshPocket";
      case 95: return "Seeed SenseCAP Solar Node";
      case 99: return "Seeed Wio Tracker L1";
      case 100: return "Seeed Wio Tracker L1 E-Ink";
      case 96: return "NomadStar Meteor Pro";
      case 97: return "Crowpanel Adv 4.3/5.0/7.0 TFT / Crowpanel Adv 2.4/2.8 TFT / Crowpanel Adv 3.5 TFT";
      case 101: return "muzi R1 Neo";
      case 102: return "LILYGO T-Deck Pro";
      case 103: return "LILYGO T-LoRa Pager";
      case 108: return "Heltec MeshSolar";
      case 109: return "LILYGO T-Echo Lite";
      case 111: return "M5Stack Unit C6L";
      case 110: return "Heltec V4";
      case 132: return "Heltec V4 R8";
      case 106: return "RAK3312";
      case 112: return "Cardputer Mesh Kit";
      case 113: return "Heltec Wireless Tracker V2";
      case 115: return "ThinkNode M3";
      case 116: return "RAK WisMesh Tap V2";
      case 117: return "RAK3401 1W / RAK WisMesh Repeater Mini V2 HP";
      case 118: return "RAK6421 Hat+";
      case 119: return "ThinkNode M4";
      case 120: return "ThinkNode M6";
      case 121: return "Elecrow Meshstick 1262";
      case 122: return "LilyGo T-Beam 1W";
      case 123: return "LilyGo T5 E-paper S3 Pro / LilyGo T5 E-paper S3 Pro V2";
      case 125: return "LilyGo Mini E-paper S3";
      case 127: return "Heltec Mesh Node T096";
      case 129: return "ThinkNode M7";
      case 134: return "Station G3";
      case 83: return "LilyGo T-Lora C6";
      case 133: return "Heltec Mesh Node T1";
      case 128: return "Seeed MeshTracker X1";
      case 130: return "Elecrow ThinkNode M8";
      case 124: return "LilyGo T-Beam BPF";
      case 131: return "Elecrow ThinkNode M9";
      case 136: return "LilyGo T-Echo-Card";
      case 114: return "T-Watch Ultra";
      case 139: return "Heltec MeshTower V2";
      case 140: return "Meshnology W10";
      case 141: return "Heltec RC32";
      case 142: return "Heltec RC52";
      case 143: return "Heltec RCC6";
      case 145: return "Meshnology W12";
      case 144: return "Seeed Wio Tracker L1 Pro 1W";
      case 137: return "Seeed Wio Tracker L2 Pro";
      case 148: return "Axiometa Genesis Mini";
      default: return "Radio model " + id + " (not in this catalog)";
    }
  }
}
